import { Router, Request, Response } from 'express';
import fs from 'fs';
import path from 'path';
import { DeployRequest } from '../models/resume.model';
import { getSiteDir } from '../generator/site.generator';

const router = Router();

// POST /api/deploy — create GitHub repo, push site files, deploy to Netlify
router.post('/deploy', async (req: Request, res: Response): Promise<void> => {
  const { siteId, repoName } = req.body as DeployRequest;

  if (!siteId || !repoName) {
    res.status(400).json({ error: 'Missing siteId or repoName.' });
    return;
  }

  const ghToken = process.env.GITHUB_TOKEN;
  const netlifyToken = process.env.NETLIFY_TOKEN;

  if (!ghToken || !netlifyToken) {
    res.status(500).json({
      error: 'Server missing GITHUB_TOKEN or NETLIFY_TOKEN environment variables.',
    });
    return;
  }

  const siteDir = getSiteDir(siteId);
  if (!fs.existsSync(siteDir)) {
    res.status(404).json({ error: 'Generated site not found. Generate the site first.' });
    return;
  }

  try {
    // 1. Create GitHub repo
    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${ghToken}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repoName,
        description: 'Personal resume website — generated by Resume Website Builder',
        private: false,
        auto_init: false,
      }),
    });

    if (!createRepoRes.ok) {
      const err = (await createRepoRes.json()) as Record<string, unknown>;
      const errors = err.errors as Array<{ message?: string }> | undefined;
      const message =
        errors?.[0]?.message || (err.message as string) || 'Failed to create GitHub repo.';
      res.status(createRepoRes.status).json({ error: message });
      return;
    }

    const repo = (await createRepoRes.json()) as { full_name: string; html_url: string };

    // 2. Read all site files and push them in a single commit
    const files = fs.readdirSync(siteDir);
    const tree: Array<{ path: string; mode: string; type: string; content: string }> = [];

    for (const file of files) {
      const filePath = path.join(siteDir, file);
      if (fs.statSync(filePath).isFile()) {
        tree.push({
          path: file,
          mode: '100644',
          type: 'blob',
          content: fs.readFileSync(filePath, 'utf-8'),
        });
      }
    }

    // Create a tree
    const createTreeRes = await fetch(
      `https://api.github.com/repos/${repo.full_name}/git/trees`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${ghToken}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ tree }),
      }
    );

    if (!createTreeRes.ok) {
      res.status(500).json({ error: 'Failed to create git tree.' });
      return;
    }

    const treeData = (await createTreeRes.json()) as { sha: string };

    // Create a commit
    const createCommitRes = await fetch(
      `https://api.github.com/repos/${repo.full_name}/git/commits`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${ghToken}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message: 'Initial commit — resume website',
          tree: treeData.sha,
        }),
      }
    );

    if (!createCommitRes.ok) {
      res.status(500).json({ error: 'Failed to create commit.' });
      return;
    }

    const commitData = (await createCommitRes.json()) as { sha: string };

    // Create the main branch ref
    const createRefRes = await fetch(
      `https://api.github.com/repos/${repo.full_name}/git/refs`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${ghToken}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ref: 'refs/heads/main',
          sha: commitData.sha,
        }),
      }
    );

    if (!createRefRes.ok) {
      res.status(500).json({ error: 'Failed to push to GitHub.' });
      return;
    }

    // 3. Deploy to Netlify using the deploy files API
    // First, create a Netlify site
    const createSiteRes = await fetch('https://api.netlify.com/api/v1/sites', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${netlifyToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repoName,
        repo: {
          provider: 'github',
          repo: repo.full_name,
          branch: 'main',
          cmd: '',
          dir: '/',
        },
      }),
    });

    let netlifyUrl: string;

    if (createSiteRes.ok) {
      const netlifySite = (await createSiteRes.json()) as {
        ssl_url?: string;
        url: string;
        id: string;
      };
      netlifyUrl = netlifySite.ssl_url || netlifySite.url;
    } else {
      // Fallback: deploy via file upload if repo linking fails
      const deployFiles: Record<string, string> = {};
      for (const file of files) {
        const filePath = path.join(siteDir, file);
        if (fs.statSync(filePath).isFile()) {
          // Netlify expects SHA1 of file content for the digest
          const content = fs.readFileSync(filePath);
          const crypto = await import('crypto');
          const sha1 = crypto.createHash('sha1').update(content).digest('hex');
          deployFiles[`/${file}`] = sha1;
        }
      }

      // Create site without repo link
      const fallbackSiteRes = await fetch('https://api.netlify.com/api/v1/sites', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${netlifyToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ name: `${repoName}-resume` }),
      });

      if (!fallbackSiteRes.ok) {
        // Still return GitHub success even if Netlify fails
        res.json({
          repoUrl: repo.html_url,
          netlifyUrl: '',
          warning: 'GitHub repo created but Netlify deployment failed.',
        });
        return;
      }

      const fallbackSite = (await fallbackSiteRes.json()) as {
        id: string;
        ssl_url?: string;
        url: string;
      };

      // Deploy with file digest
      const deployRes = await fetch(
        `https://api.netlify.com/api/v1/sites/${fallbackSite.id}/deploys`,
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${netlifyToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ files: deployFiles }),
        }
      );

      if (deployRes.ok) {
        const deployData = (await deployRes.json()) as {
          id: string;
          required: string[];
        };

        // Upload required files
        for (const sha of deployData.required) {
          const matchingFile = Object.entries(deployFiles).find(
            ([, hash]) => hash === sha
          );
          if (matchingFile) {
            const fileName = matchingFile[0].replace('/', '');
            const fileContent = fs.readFileSync(path.join(siteDir, fileName));
            await fetch(
              `https://api.netlify.com/api/v1/deploys/${deployData.id}/files${matchingFile[0]}`,
              {
                method: 'PUT',
                headers: {
                  Authorization: `Bearer ${netlifyToken}`,
                  'Content-Type': 'application/octet-stream',
                },
                body: fileContent,
              }
            );
          }
        }
      }

      netlifyUrl = fallbackSite.ssl_url || fallbackSite.url;
    }

    res.json({
      repoUrl: repo.html_url,
      netlifyUrl,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Deploy failed.';
    res.status(500).json({ error: message });
  }
});

export default router;
